name: 'Markdown To JobSummary'
description: 'Takes a markdown input file and publishes it to a github workflows job summary'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  action:
    description: 'Name of the action (if named)'
    required: false
  file:
    description: 'Name of the markdownfile to append to the job summary'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JBang
      uses: jbangdev/setup-jbang@main
    - name: Run the action
      id: action
      run: jbang --java 21 --fresh --repos 'github=https://maven.pkg.github.com/janpk/md-to-jobsummary/' --repos 'mavencentral' dev.hagastua.action:md-to-jobsummary:1.0.1-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
